# Generated by Django 5.1.2 on 2024-10-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartticket",
            name="price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
