# Generated by Django 5.1.2 on 2024-10-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_cartticket_price_ticket_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateTimeField(default="2024-12-15T19:00:00"),
        ),
    ]
