# Generated by Django 5.1.2 on 2024-10-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0006_event_image_hall_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="sectors_image",
            field=models.ImageField(default=0, upload_to=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
